export enum ActionTypes {
  REQUEST_COMMITS = 'REQUEST_COMMITS',
  RECEIVE_COMMITS = 'RECEIVE_COMMITS',
  SELECT_PATH = 'SELECT_PATH',
  INVALIDATE_PATH = 'INVALIDATE_PATH',
  HIGHLIGHT_COMMIT = 'HIGHLIGHT_COMMIT',
  VIEW_COMMITS = 'VIEW_COMMITS',
  VIEW_FILES = 'VIEW_FILES',
  ADD_AUTHOR_FILTER = 'ADD_AUTHOR_FILTER',
  REMOVE_AUTHOR_FILTER = 'REMOVE_AUTHOR_FILTER',
  REMOVE_ALL_AUTHOR_FILTERS = 'REMOVE_ALL_AUTHOR_FILTERS',
  SET_AUTHORS_CONTAINER_FILTER = 'SET_AUTHORS_CONTAINER_FILTER',
  SET_AUTHORS_CONTAINER_SORT = 'SET_AUTHORS_CONTAINER_SORT',
  SET_AUTHORS_CONTAINER_SEARCH = 'SET_AUTHORS_CONTAINER_SEARCH',
  SET_COMMITS_CONTAINER_SORT = 'SET_COMMITS_CONTAINER_SORT',
  SET_COMMITS_CONTAINER_SEARCH = 'SET_COMMITS_CONTAINER_SEARCH',
  SET_FILES_CONTAINER_SORT = 'SET_FILES_CONTAINER_SORT',
  SET_FILES_CONTAINER_SEARCH = 'SET_FILES_CONTAINER_SEARCH',
}

export enum AuthorsContainerSorts {
  TIME = 'time',
  LINES = 'lines',
  COMMITS = 'commits',
}

export enum CommitsContainerSorts {
  TIME = 'time',
  LINES = 'lines',
}

export enum FilesContainerSorts {
  TIME = 'time',
  LINES = 'lines',
  COMMITS = 'commits',
}

export enum AuthorsContainerFilters {
  ALL = 'all',
  FILTERED = 'filtered',
}
